---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: catalyst-ui
  namespace: catalyst
  labels:
    app: catalyst-ui
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`catalyst.talos00`)
      kind: Rule
      services:
        - name: catalyst-ui
          port: 80
